### PR TITLE
B1.0 pre5 -- JS9 install release fix

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Comment by Athanaseus** [comment]
Does it also need a version bump?

**Comment by o-smirnov** [comment]
I dunno, does it need a version bump to go on PyPI? I deleted the release/tag and re-created it. But it's not on PyPI yet.

**Comment by Athanaseus** [comment]
Yes, it does, unless the version on _PyPI_ is purged too. I don't have the privilege to do so. Otherwise, it will complain that the version exists.

**Comment by o-smirnov** [comment]
OK, rc6 it is then.

**Pull request merged**
