### PR TITLE
B1.0 pre5

### LINKED ISSUE #61: this wheel's on fire
[(For those too young to get the reference...)](https://www.youtube.com/watch?v=-mlzUHxNMV8)

So this currently happens when I pip install it, see below.

In summary, it tries to build a wheel for radiopadre, falls over because it can't find jupyter, then goes on to run setup.py for radiopadre normally, and succeeds in the end.

I don't fully (or even partially) understand WTF a wheel is, but it's clearly (a) entirely optional, (b) currently un-buildable, and so (c) should be disabled?

(Actually the same thing happens for pyregions or whatsit, but that's not our baby...)

```
radiopadre.client [29.00s]: young: Building wheels for collected packages: radiopadre
radiopadre.client [29.01s]: young:   Building wheel for radiopadre (setup.py): started
radiopadre.client [29.81s]: young:   Building wheel for radiopadre (setup.py): finished with status 'error'
radiopadre.client [29.82s]: young:   Running setup.py clean for radiopadre
radiopadre.client [29.82s]: young stderr:   ERROR: Command errored out with exit status 1:
radiopadre.client [29.82s]: young stderr:    command: /home/oms/.radiopadre/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kyxmrynr/radiopadre/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kyxmrynr/radiopadre/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6w5yazqz
radiopadre.client [29.82s]: young stderr:        cwd: /tmp/pip-install-kyxmrynr/radiopadre/
radiopadre.client [29.83s]: young stderr:   Complete output (126 lines):
radiopadre.client [29.83s]: young stderr:   /home/oms/.radiopadre/venv/lib/python3.6/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '1.0-pre4' to '1.0rc4'
radiopadre.client [29.83s]: young stderr:     normalized_version,
radiopadre.client [29.83s]: young stderr:   running bdist_wheel
radiopadre.client [29.83s]: young stderr:   running build
radiopadre.client [29.83s]: young stderr:   running build_py
radiopadre.client [29.83s]: young stderr:   creating build
radiopadre.client [29.83s]: young stderr:   creating build/lib
radiopadre.client [29.83s]: young stderr:   creating build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/render.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/layouts.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/table.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/datadir.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/imagefile.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/file.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/filelist.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/pdffile.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/notebook.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/htmlfile.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/textfile.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/settings_manager.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/__init__.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/casatable.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   copying radiopadre/fitsfile.py -> build/lib/radiopadre
radiopadre.client [29.83s]: young stderr:   creating build/lib/radiopadre_kernel
radiopadre.client [29.83s]: young stderr:   copying radiopadre_kernel/__init__.py -> build/lib/radiopadre_kernel
radiopadre.client [29.83s]: young stderr:   creating build/lib/radiopadre_utils
radiopadre.client [29.83s]: young stderr:   copying radiopadre_utils/notebook_utils.py -> build/lib/radiopadre_utils
radiopadre.client [29.83s]: young stderr:   copying radiopadre_utils/__init__.py -> build/lib/radiopadre_utils
radiopadre.client [29.83s]: young stderr:   running build_scripts
radiopadre.client [29.83s]: young stderr:   creating build/scripts-3.6
radiopadre.client [29.83s]: young stderr:   copying and adjusting bin/deprecated-install-radiopadre -> build/scripts-3.6
radiopadre.client [29.83s]: young stderr:   copying and adjusting bin/install-js9-colormaps -> build/scripts-3.6
radiopadre.client [29.83s]: young stderr:   copying and adjusting bin/setup-radiopadre-virtualenv -> build/scripts-3.6
radiopadre.client [29.83s]: young stderr:   copying and adjusting bin/deprecated-run-remote-padre -> build/scripts-3.6
radiopadre.client [29.83s]: young stderr:   copying and adjusting bin/bootstrap-radiopadre-install -> build/scripts-3.6
radiopadre.client [29.83s]: young stderr:   copying and adjusting bin/radiopadre-http-server.py -> build/scripts-3.6
radiopadre.client [29.83s]: young stderr:   copying and adjusting bin/deprecated-run-radiopadre -> build/scripts-3.6
radiopadre.client [29.83s]: young stderr:   changing mode of build/scripts-3.6/deprecated-install-radiopadre from 664 to 775
radiopadre.client [29.83s]: young stderr:   changing mode of build/scripts-3.6/install-js9-colormaps from 664 to 775
radiopadre.client [29.83s]: young stderr:   changing mode of build/scripts-3.6/setup-radiopadre-virtualenv from 664 to 775
radiopadre.client [29.83s]: young stderr:   changing mode of build/scripts-3.6/deprecated-run-remote-padre from 664 to 775
radiopadre.client [29.83s]: young stderr:   changing mode of build/scripts-3.6/bootstrap-radiopadre-install from 664 to 775
radiopadre.client [29.83s]: young stderr:   changing mode of build/scripts-3.6/radiopadre-http-server.py from 664 to 775
radiopadre.client [29.83s]: young stderr:   changing mode of build/scripts-3.6/deprecated-run-radiopadre from 664 to 775
radiopadre.client [29.83s]: young stderr:   installing to build/bdist.linux-x86_64/wheel
radiopadre.client [29.83s]: young stderr:   running install
radiopadre.client [29.83s]: young stderr:   running install_lib
radiopadre.client [29.83s]: young stderr:   creating build/bdist.linux-x86_64
radiopadre.client [29.83s]: young stderr:   creating build/bdist.linux-x86_64/wheel
radiopadre.client [29.83s]: young stderr:   creating build/bdist.linux-x86_64/wheel/radiopadre_kernel
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre_kernel/__init__.py -> build/bdist.linux-x86_64/wheel/radiopadre_kernel
radiopadre.client [29.83s]: young stderr:   creating build/bdist.linux-x86_64/wheel/radiopadre_utils
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre_utils/notebook_utils.py -> build/bdist.linux-x86_64/wheel/radiopadre_utils
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre_utils/__init__.py -> build/bdist.linux-x86_64/wheel/radiopadre_utils
radiopadre.client [29.83s]: young stderr:   creating build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/render.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/layouts.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/table.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/datadir.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/imagefile.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/file.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/filelist.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/pdffile.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/notebook.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/htmlfile.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/textfile.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/settings_manager.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/__init__.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/casatable.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   copying build/lib/radiopadre/fitsfile.py -> build/bdist.linux-x86_64/wheel/radiopadre
radiopadre.client [29.83s]: young stderr:   running install_egg_info
radiopadre.client [29.83s]: young stderr:   running egg_info
radiopadre.client [29.83s]: young stderr:   writing radiopadre.egg-info/PKG-INFO
radiopadre.client [29.83s]: young stderr:   writing dependency_links to radiopadre.egg-info/dependency_links.txt
radiopadre.client [29.83s]: young stderr:   writing requirements to radiopadre.egg-info/requires.txt
radiopadre.client [29.83s]: young stderr:   writing top-level names to radiopadre.egg-info/top_level.txt
radiopadre.client [29.83s]: young stderr:   reading manifest file 'radiopadre.egg-info/SOURCES.txt'
radiopadre.client [29.83s]: young stderr:   reading manifest template 'MANIFEST.in'
radiopadre.client [29.83s]: young stderr:   writing manifest file 'radiopadre.egg-info/SOURCES.txt'
radiopadre.client [29.83s]: young stderr:   Copying radiopadre.egg-info to build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4-py3.6.egg-info
radiopadre.client [29.83s]: young stderr:   running install_scripts
radiopadre.client [29.83s]: young stderr:   creating build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data
radiopadre.client [29.84s]: young stderr:   creating build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts
radiopadre.client [29.84s]: young stderr:   copying build/scripts-3.6/deprecated-install-radiopadre -> build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts
radiopadre.client [29.84s]: young stderr:   copying build/scripts-3.6/install-js9-colormaps -> build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts
radiopadre.client [29.84s]: young stderr:   copying build/scripts-3.6/setup-radiopadre-virtualenv -> build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts
radiopadre.client [29.84s]: young stderr:   copying build/scripts-3.6/deprecated-run-remote-padre -> build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts
radiopadre.client [29.84s]: young stderr:   copying build/scripts-3.6/bootstrap-radiopadre-install -> build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts
radiopadre.client [29.84s]: young stderr:   copying build/scripts-3.6/radiopadre-http-server.py -> build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts
radiopadre.client [29.84s]: young stderr:   copying build/scripts-3.6/deprecated-run-radiopadre -> build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts
radiopadre.client [29.84s]: young stderr:   changing mode of build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts/deprecated-install-radiopadre to 775
radiopadre.client [29.84s]: young stderr:   changing mode of build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts/install-js9-colormaps to 775
radiopadre.client [29.84s]: young stderr:   changing mode of build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts/setup-radiopadre-virtualenv to 775
radiopadre.client [29.84s]: young stderr:   changing mode of build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts/deprecated-run-remote-padre to 775
radiopadre.client [29.84s]: young stderr:   changing mode of build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts/bootstrap-radiopadre-install to 775
radiopadre.client [29.84s]: young stderr:   changing mode of build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts/radiopadre-http-server.py to 775
radiopadre.client [29.84s]: young stderr:   changing mode of build/bdist.linux-x86_64/wheel/radiopadre-1.0rc4.data/scripts/deprecated-run-radiopadre to 775
radiopadre.client [29.84s]: young stderr:   WARNING: Package(s) not found: jupyter
radiopadre.client [29.84s]: young stderr:   setup-radiopadre-virtualenv: Setting up radiopadre inside virtualenv /home/oms/.radiopadre/venv
radiopadre.client [29.84s]: young stderr:   Traceback (most recent call last):
radiopadre.client [29.84s]: young stderr:     File "./bin/setup-radiopadre-virtualenv", line 98, in <module>
radiopadre.client [29.84s]: young stderr:       raise subprocess.CalledProcessError(-1, "jupyter", "no jupyter found")
radiopadre.client [29.84s]: young stderr:   subprocess.CalledProcessError: Command 'jupyter' died with <Signals.SIGHUP: 1>.
radiopadre.client [29.84s]: young stderr:   Traceback (most recent call last):
radiopadre.client [29.84s]: young stderr:     File "<string>", line 1, in <module>
radiopadre.client [29.84s]: young stderr:     File "/tmp/pip-install-kyxmrynr/radiopadre/setup.py", line 54, in <module>
radiopadre.client [29.84s]: young stderr:       "Programming Language :: Python :: 3.6",
radiopadre.client [29.84s]: young stderr:     File "/home/oms/.radiopadre/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
radiopadre.client [29.84s]: young stderr:       return distutils.core.setup(**attrs)
radiopadre.client [29.84s]: young stderr:     File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
radiopadre.client [30.17s]: young: Failed to build radiopadre
radiopadre.client [30.84s]: young: Installing collected packages: pillow, numpy, python-dateutil, cycler, pyparsing, kiwisolver, matplotlib, astropy, decorator, networkx, PyWavelets, imageio, scipy, scikit-image, astropy-healpix, reproject, Cython, pyregion, pyavm, shapely, APLpy, backcall, ptyprocess, pexpect, wcwidth, prompt-toolkit, pygments, pickleshare, ipython-genutils, traitlets, parso, jedi, ipython, tornado, pyzmq, jupyter-core, jupyter-client, ipykernel, zipp, importlib-metadata, pyrsistent, attrs, jsonschema, nbformat, webencodings, bleach, entrypoints, pandocfilters, MarkupSafe, jinja2, mistune, testpath, defusedxml, nbconvert, terminado, Send2Trash, prometheus-client, notebook, widgetsnbextension, ipywidgets, jupyter-console, qtconsole, jupyter, argparse, future, python-casacore, radiopadre
radiopadre.client [56.30s]: young:     Running setup.py install for radiopadre: started
radiopadre.client [116.85s]: young:     Running setup.py install for radiopadre: still running...
```

### PR DESCRIPTION
**Pull request by Athanaseus**
Should fix #61

### CODE REVIEW

**Comment by o-smirnov** [comment]
@Athanaseus: looking at this build https://travis-ci.org/ratt-ru/radiopadre/jobs/656319201?utm_source=github_status

...it's still trying to build a wheel and failing with jupyter not found.

**Comment by Athanaseus** [comment]
> @Athanaseus: looking at this build https://travis-ci.org/ratt-ru/radiopadre/jobs/656319201?utm_source=github_status
> 
> ...it's still trying to build a wheel and failing with jupyter not found.

I'll look into this in-depth, I'm suspecting that the customized `setup.py` has to do with this.

**Comment by Athanaseus** [comment]
Approved.

@o-smirnov should I proceed and remove the wheel distribution? I figured out a way to build then successfully or get rid of them completely.

**Comment by o-smirnov** [comment]
OK cool, so as discussed let's just disable the wheels (travis is currently failing on that), and push the pre5 release.

**Comment by Athanaseus** [comment]
This is ready for shipping. No wheels firing.

A custom class is now defined. It throws only a warning instead of an error that no (`.whl`) files are produced. 

@o-smirnov is this issue (https://github.com/kernsuite/packaging/issues/176) still barrier?
i.e. astropy             #<2.0.11
Might relate to https://github.com/numpy/numpy/issues/11871 (Or numpy version)

Also this https://github.com/jupyter/notebook/issues/4303 seems like it's resolved.
i.e. notebook            #<5.7.3

**Comment by o-smirnov** [comment]
All those issues seem to have resolved (which is why the hard version requirement has been commented out). I'm going to push the release button on this.

**Comment by o-smirnov** [comment]
@Athanaseus now that it's merged, I'm getting a travis failure but a weird one, "PyPI upload failed."

**Comment by o-smirnov** [comment]
See here: https://travis-ci.org/ratt-ru/radiopadre/jobs/657656565

Any idea what's going on?

**Comment by adrianjhpc** [comment]
Might need an upgrade of setuptools?

**Comment by Athanaseus** [comment]
Ah I added the README as part of the package long description so that it gets rendered on _PYPI_. My bad the error above is due to _PYPI_ not supporting `.md` instead, it requires `.rst`. Should I remove that part for now or maybe invest some time in porting it? reStructuredText is also good for writing complex documents that auto-generating doc tools like Sphinx can interpret. But maybe this can come later with the next tractor implementing `readthedocs`?

**Pull request merged**
