### PR TITLE
B1.0 pre5

### PR DESCRIPTION
**Pull request by Athanaseus**
Converts README to rst format.

### CODE REVIEW

**Comment by Athanaseus** [comment]
@o-smirnov you can review and merge. Then re-tag.

**Comment by o-smirnov** [comment]
Heh, I just realized this README is anti-documentation... let me fix it before we push the release...

**Comment by o-smirnov** [comment]
@Athanaseus same failure on Travis though. https://travis-ci.org/ratt-ru/radiopadre/jobs/657656565?utm_medium=notification&utm_source=email

**Comment by Athanaseus** [comment]
No wait, it looks like it never built the new `Reveal++` tag. The tag still says 7 commits behind master. Can I purge it, and repeat what you did?

**Comment by o-smirnov** [comment]
Sure. Maybe we need to release a pre6?

**Comment by Athanaseus** [comment]
Done. https://pypi.org/project/radiopadre/.

PS: The removal of a github tag on the site is a two-step process (1st removes release & 2nd removes tag). So what happened is that that only the release was removed, and when a new release was made with the same version it used the same tag. And since this tag was built before it never builds it again,  then I tried re-triggering the build, but since it was the same as previous it resulted with the error above.

**Pull request merged**
